# Generated by Django 3.2.14 on 2023-11-16 07:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('image', models.ImageField(db_column='image', null=True, upload_to='company_images')),
                ('address', models.CharField(db_column='address', default='', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='website.company')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='FreeBoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_column='type_name', max_length=255)),
            ],
            options={
                'db_table': 'freeboard_type',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('content', models.TextField(db_column='content')),
                ('top_flag', models.CharField(db_column='top_flag', default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='website.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_root', models.CharField(db_column='reg_root', default='', max_length=15)),
                ('phone_no', models.CharField(db_column='phone_no', default='', max_length=15, null=True)),
                ('image', models.ImageField(db_column='image', upload_to='profile_images')),
                ('note', models.TextField(db_column='note', null=True)),
                ('check_flag', models.CharField(db_column='check_flag', default='0', max_length=10)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='website.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('content', models.TextField(db_column='content')),
                ('anonymous_flag', models.CharField(db_column='anonymous_flag', default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('board_type', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='freeboard_type', to='website.freeboardtype')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='freeboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freeboard',
            },
        ),
        migrations.CreateModel(
            name='BoradReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(db_column='reply', default='', null=True)),
                ('hidden', models.CharField(db_column='hidden', default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('freeboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.freeboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_reply',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_time', models.CharField(db_column='attend_time', default=datetime.time(16, 18, 19, 356064), max_length=250)),
                ('leave_time', models.CharField(db_column='leave_time', default='', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
