# Generated by Django 3.2.14 on 2023-05-30 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(db_column='phone_no', default='', max_length=15, null=True)),
                ('resume', models.FileField(db_column='resume', upload_to='resume')),
                ('image', models.ImageField(db_column='image', upload_to='images')),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('department', models.CharField(db_column='department', max_length=255)),
                ('note', models.TextField(db_column='note', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
