# Generated by Django 3.2.14 on 2023-11-17 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(15, 46, 24, 522821), max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='profile_images'),
        ),
    ]
