# Generated by Django 3.2.14 on 2023-05-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20230530_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='check_flag',
            field=models.CharField(db_column='check_flag', default='0', max_length=10),
        ),
    ]
