# Generated by Django 3.2.14 on 2024-03-28 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_attendance_attend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(15, 44, 17, 868696), max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='website.department'),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('manager_flag', models.BooleanField(db_column='manager_flag')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='website.department')),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='website.rank'),
        ),
    ]
