# Generated by Django 3.2.14 on 2024-03-29 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240328_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(15, 38, 36, 140), max_length=250),
        ),
    ]
