# Generated by Django 3.2.14 on 2023-06-15 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(11, 31, 55, 661403), max_length=250),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_time',
            field=models.CharField(db_column='leave_time', default='', max_length=250, null=True),
        ),
    ]
