# Generated by Django 3.2.14 on 2023-09-05 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20230905_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('content', models.TextField(db_column='content')),
                ('top_flag', models.CharField(db_column='top_flag', default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.AddField(
            model_name='boradreply',
            name='hidden',
            field=models.CharField(db_column='hidden', default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(14, 10, 37, 963708), max_length=250),
        ),
    ]
