# Generated by Django 3.2.14 on 2023-09-05 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20230905_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(14, 11, 7, 921483), max_length=250),
        ),
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
    ]
