# Generated by Django 3.2.14 on 2023-09-06 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20230905_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_column='type_name', max_length=255)),
            ],
            options={
                'db_table': 'freeboard_type',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(15, 8, 11, 816597), max_length=250),
        ),
    ]
