# Generated by Django 3.2.14 on 2023-09-06 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20230906_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='board_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='freeboard_type', to='website.freeboardtype'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(15, 12, 48, 27878), max_length=250),
        ),
    ]
