# Generated by Django 3.2.14 on 2023-09-06 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20230906_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='anonymous_flag',
            field=models.CharField(db_column='anonymous_flag', default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(15, 29, 42, 75497), max_length=250),
        ),
    ]
