# Generated by Django 3.2.14 on 2023-09-06 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_auto_20230906_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(17, 50, 34, 494219), max_length=250),
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freeboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
