# Generated by Django 3.2.14 on 2023-09-06 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0018_auto_20230906_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(17, 53, 3, 32355), max_length=250),
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='freeboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
