# Generated by Django 3.2.14 on 2023-09-16 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20230906_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(17, 26, 33, 274542), max_length=250),
        ),
    ]
