# Generated by Django 3.2.14 on 2023-11-09 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_attendance_attend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(db_column='attend_time', default=datetime.time(10, 31, 3, 836194), max_length=250),
        ),
    ]
