DATABASE:
  ENGINE: django.db.backends.mysql
  NAME: hr_project
  USER: root
  PASSWORD : "1234"
  HOST : 127.0.0.1
  PORT : 3306

SOCIAL_AUTH_GOOGLE_CLIENT_ID : "845622536191-k5bn9m9d9vmso6v8q8s70mo3lg6cfv1t.apps.googleusercontent.com"

SOCIAL_AUTH_GOOGLE_SECRET : "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"

STATE : "google login"

# 위도 경도 찾기 api
IPSTACK_API_KEY : ed4b8e0b70b8f9da08bc61b4e3a51dc6

# 위도
LATITUDE : 37.50831227647185
# 경도
LONGITUDE : 127.11131230010045 
