DATABASE:
  ENGINE: django.db.backends.mysql
  NAME: hr_project
  USER: root
  PASSWORD : "1234"
  HOST : 127.0.0.1
  PORT : 3306


# 위도 경도 찾기 api
IPSTACK_API_KEY : ed4b8e0b70b8f9da08bc61b4e3a51dc6

# 위도
LATITUDE : 37.50831227647185
# 경도
LONGITUDE : 127.11131230010045 
